export enum UserRole {
  CUSTOMER = "CUSTOMER",
  RESTAURANT = "RESTAURANT",
  DELIVERY = "DELIVERY",
  DRIVER = "DRIVER",
  SUPPORT = "SUPPORT",
  FINANCE = "FINANCE",
  ADMIN = "ADMIN",
  SUPER_ADMIN = "SUPER_ADMIN",
}

export enum AdminType {
  ADMIN = "ADMIN",
  SUPER_ADMIN = "SUPER_ADMIN",
}

export enum StoreType {
  FOOD = "FOOD",
  GROCERY = "GROCERY",
  PHARMACY = "PHARMACY",
}

export enum VehicleType {
  BIKE = "BIKE",
  AUTO = "AUTO",
  CAB = "CAB",
}

export enum PaymentMethod {
  WALLET = "WALLET",
  CASH = "CASH",
  ONLINE = "ONLINE",
}

export enum PaymentStatus {
  PENDING = "PENDING",
  AUTHORIZED = "AUTHORIZED",
  PAID = "PAID",
  FAILED = "FAILED",
  REFUNDED = "REFUNDED",
  CANCELLED = "CANCELLED",
}

export enum ServiceType {
  FOOD = "FOOD",
  GROCERY = "GROCERY",
  PHARMACY = "PHARMACY",
  RIDE = "RIDE",
  COURIER = "COURIER",
  HOME_SERVICE = "HOME_SERVICE",
}

export enum ErrorCode {
  VALIDATION_ERROR = "VALIDATION_ERROR",
  UNAUTHENTICATED = "UNAUTHENTICATED",
  FORBIDDEN = "FORBIDDEN",
  NOT_FOUND = "NOT_FOUND",
  CONFLICT = "CONFLICT",
  RATE_LIMITED = "RATE_LIMITED",
  IDEMPOTENCY_CONFLICT = "IDEMPOTENCY_CONFLICT",
  PAYMENT_FAILED = "PAYMENT_FAILED",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
}